# Jupyter notebooks

Start with
  ipython notebook
and navigate with your web browser to 127.0.0.1:8888
More documentation is available in 
  http://ipython.org/notebook.html
  http://ipython.org/ipython-doc/stable/install/install.html

Alternatively, you can copy any code into a text file, and run it standalone with 
  python my_file.py

# Numpy
* Objectives of this file: np basics
 * Arrays
 * File I/o
 
## Arrays

In [1]:
# Demonstration 0: Create an array and vectorized arithmetic operations
import numpy as np
x = np.linspace(-5,5,30) # create 30 points from -5 to 5, uniformly spaced
y = x*x - 2*x
print x
print y

[-5.         -4.65517241 -4.31034483 -3.96551724 -3.62068966 -3.27586207
 -2.93103448 -2.5862069  -2.24137931 -1.89655172 -1.55172414 -1.20689655
 -0.86206897 -0.51724138 -0.17241379  0.17241379  0.51724138  0.86206897
  1.20689655  1.55172414  1.89655172  2.24137931  2.5862069   2.93103448
  3.27586207  3.62068966  3.96551724  4.31034483  4.65517241  5.        ]
[ 35.          30.98097503  27.19976219  23.65636147  20.35077289
  17.28299643  14.4530321   11.8608799    9.50653983   7.39001189
   5.51129608   3.87039239   2.46730083   1.3020214    0.3745541
  -0.31510107  -0.76694411  -0.98097503  -0.95719382  -0.69560048
  -0.19619501   0.54102259   1.51605232   2.72889417   4.17954816
   5.86801427   7.79429251   9.95838288  12.36028537  15.        ]


In [9]:
# Things you can do with arrays
#    - index their elements
print x[5]
#    - perform arithmetic operations on all elements, without an explicit loop
print x+1
#    - ask their size
print [len(x), x.shape]
#    - request parts of an array
print x[:3]
print x[3:7]
z = x[:-3]   # Negative number <=> index n - 1
print len(z), len(x)

-3.27586206897
[-4.         -3.65517241 -3.31034483 -2.96551724 -2.62068966 -2.27586207
 -1.93103448 -1.5862069  -1.24137931 -0.89655172 -0.55172414 -0.20689655
  0.13793103  0.48275862  0.82758621  1.17241379  1.51724138  1.86206897
  2.20689655  2.55172414  2.89655172  3.24137931  3.5862069   3.93103448
  4.27586207  4.62068966  4.96551724  5.31034483  5.65517241  6.        ]
[30, (30,)]
[-5.         -4.65517241 -4.31034483]
[-3.96551724 -3.62068966 -3.27586207 -2.93103448]
27 30


In [15]:
# Arrays are NOT lists
#   - lists:  + becomes CONCATENATION
#     arrays: + is element-by-element addition
a = [1,2,3]
b = [99,100]
print a+b
# You can convert a list to an array
c = np.array(a+b)
print c+c  # now + operator is element-by-element addition

[1, 2, 3, 99, 100]
[  2   4   6 198 200]


## File I/o
numpy provides tools to load and save ascii arrays

In [22]:
# Horrible, but it works
dat = np.array( [x,y]).T
#print dat
print dat.shape, x.shape
dat0 = np.array( [x,y]);
print dat0.shape

# Less horrible, and you learn something
dat = np.zeros( (len(x),2))
dat[:,0] =x
dat[:,1] =y
print dat


np.savetxt("my-file.dat", dat)

(30, 2) (30,)
(2, 30)
[[ -5.          35.        ]
 [ -4.65517241  30.98097503]
 [ -4.31034483  27.19976219]
 [ -3.96551724  23.65636147]
 [ -3.62068966  20.35077289]
 [ -3.27586207  17.28299643]
 [ -2.93103448  14.4530321 ]
 [ -2.5862069   11.8608799 ]
 [ -2.24137931   9.50653983]
 [ -1.89655172   7.39001189]
 [ -1.55172414   5.51129608]
 [ -1.20689655   3.87039239]
 [ -0.86206897   2.46730083]
 [ -0.51724138   1.3020214 ]
 [ -0.17241379   0.3745541 ]
 [  0.17241379  -0.31510107]
 [  0.51724138  -0.76694411]
 [  0.86206897  -0.98097503]
 [  1.20689655  -0.95719382]
 [  1.55172414  -0.69560048]
 [  1.89655172  -0.19619501]
 [  2.24137931   0.54102259]
 [  2.5862069    1.51605232]
 [  2.93103448   2.72889417]
 [  3.27586207   4.17954816]
 [  3.62068966   5.86801427]
 [  3.96551724   7.79429251]
 [  4.31034483   9.95838288]
 [  4.65517241  12.36028537]
 [  5.          15.        ]]
